var No = 11;
console.log(No);
console.log(typeof No);
No = 21;
console.log(No);
console.log(typeof No);
var Data = true;
console.log(Data);
console.log(typeof Data);
var temp = 90.8564;
console.log(temp);
console.log(typeof temp);
var str = "A";
console.log(str);
console.log(typeof (str));
str = 'Marvellous';
console.log(str);
console.log(typeof (str));
